export const TOKEN_VALUES = {
  "--color-background": "#FAFAF8",
  "--color-ink": "#14161A",
  "--color-muted": "#6A6E78",
  "--color-card": "#FFFFFF",
  "--color-line": "#E6E5E1",
  "--color-accent": "#14161A",
  "--color-accent-text": "#FFFFFF",
  "--color-focus-ring": "#14161A",
  "--font-headline": "Georgia, serif",
  "--font-body": "-apple-system, BlinkMacSystemFont, " + '"Segoe UI", sans-serif',
  "--font-size-question": "26px",
  "--font-size-welcome": "32px",
  "--font-size-option-label": "15px",
  "--font-size-option-description": "13px",
  "--font-size-helper": "14px",
  "--font-size-button": "15px",
  "--font-size-step-counter": "13px",
  "--font-line-height-question": "1.25",
  "--font-line-height-welcome": "1.2",
  "--font-line-height-option-label": "1.4",
  "--font-line-height-option-description": "1.45",
  "--font-line-height-helper": "1.5",
  "--font-line-height-button": "1",
  "--font-line-height-step-counter": "1",
  "--font-weight-regular": "400",
  "--font-weight-medium": "500",
  "--space-1": "8px",
  "--space-2": "12px",
  "--space-3": "16px",
  "--space-4": "24px",
  "--space-5": "32px",
  "--radius-tile": "14px",
  "--radius-button": "10px",
  "--radius-pill": "999px",
  "--motion-instant": "100ms",
  "--motion-fast": "160ms",
  "--motion-base": "240ms",
  "--motion-slow": "340ms",
  "--ease-entrance": "cubic-bezier(0.2, 0, 0, 1)",
  "--ease-exit": "cubic-bezier(0.4, 0, 1, 1)",
  "--ease-standard": "cubic-bezier(0.2, 0, 0.2, 1)",
  "--stagger-step": "36ms",
  "--stagger-max": "216ms"
} as const;

/** The names of all synchronized design tokens */
export type TokenName = keyof typeof TOKEN_VALUES;
